-- O cadastro completo do album ja esta em supabase/schema.sql.
-- Execute schema.sql no SQL Editor do Supabase para criar tabelas,
-- relacionamentos, politicas, realtime e os 994 codigos de figurinhas.
