alter table public.stickers
  add column if not exists nome text;

with sticker_names(codigo, nome) as (
  values
    ('00', 'Logo'),
    ('FWC1', 'Emblema Oficial'),
    ('FWC2', 'Emblema Oficial'),
    ('FWC3', 'Mascotes Oficiais'),
    ('FWC4', 'Slogan Oficial'),
    ('FWC5', 'Bola Oficial'),
    ('FWC6', 'Emblema do País-Sede'),
    ('FWC7', 'Emblema do País-Sede'),
    ('FWC8', 'Emblema do País-Sede'),
    ('FWC9', 'FWC ITALY 1934'),
    ('FWC10', 'FWC BRAZIL 1950'),
    ('FWC11', 'FWC SWITZERLAND 1954'),
    ('FWC12', 'FWC CHILE 1962'),
    ('FWC13', 'FWC GERMANY 1974'),
    ('FWC14', 'FWC MEXICO 1986'),
    ('FWC15', 'FWC USA 1994'),
    ('FWC16', 'FWC KOREA/JAPAN 2002'),
    ('FWC17', 'FWC GERMANY 2006'),
    ('FWC18', 'FWC BRAZIL 2014'),
    ('FWC19', 'FWC QATAR 2022'),
    ('MEX1', 'Mexico Emblem'),
    ('MEX2', 'Luis Malagón'),
    ('MEX3', 'Johan Vásquez'),
    ('MEX4', 'Jorge Sánchez'),
    ('MEX5', 'César Montes'),
    ('MEX6', 'Jesús Gallardo'),
    ('MEX7', 'Israel Reyes'),
    ('MEX8', 'Diego Lainez'),
    ('MEX9', 'Carlos Rodríguez'),
    ('MEX10', 'Edson Álvarez'),
    ('MEX11', 'Orbelín Pineda'),
    ('MEX12', 'Marcel Ruiz'),
    ('MEX13', 'Team Photo'),
    ('MEX14', 'Erick Sánchez'),
    ('MEX15', 'Hirving Lozano'),
    ('MEX16', 'Santiago Giménez'),
    ('MEX17', 'Raúl Jiménez'),
    ('MEX18', 'Alexis Vega'),
    ('MEX19', 'Roberto Alvarado'),
    ('MEX20', 'César Huerta'),
    ('RSA1', 'South Africa Emblem'),
    ('RSA2', 'Ronwen Williams'),
    ('RSA3', 'Sipho Chaine'),
    ('RSA4', 'Aubrey Modiba'),
    ('RSA5', 'Samukele Kabini'),
    ('RSA6', 'Mbekezeli Mbokazi'),
    ('RSA7', 'Khulumani Ndamane'),
    ('RSA8', 'Siyabonga Ngezana'),
    ('RSA9', 'Khuliso Mudau'),
    ('RSA10', 'Nkosinathi Sibisi'),
    ('RSA11', 'Tebogo Mokoena'),
    ('RSA12', 'Thalente Mbatha'),
    ('RSA13', 'Team Photo'),
    ('RSA14', 'Bathusi Aubaas'),
    ('RSA15', 'Vaya Sithole'),
    ('RSA16', 'Sipho Mbule'),
    ('RSA17', 'Lyle Foster'),
    ('RSA18', 'Iqraam Rayners'),
    ('RSA19', 'Mohau Nkota'),
    ('RSA20', 'Oswin Appollis'),
    ('KOR1', 'South Korea Emblem'),
    ('KOR2', 'Hyeonwoo Jo'),
    ('KOR3', 'Seunggyu Kim'),
    ('KOR4', 'Minjae Kim'),
    ('KOR5', 'Yumin Cho'),
    ('KOR6', 'Youngwoo Seol'),
    ('KOR7', 'Hanbeom Lee'),
    ('KOR8', 'Taeseok Lee'),
    ('KOR9', 'Myungjae Lee'),
    ('KOR10', 'Jaesung Lee'),
    ('KOR11', 'Inbeom Hwang'),
    ('KOR12', 'Kangin Lee'),
    ('KOR13', 'Team Photo'),
    ('KOR14', 'Seungho Paik'),
    ('KOR15', 'Jens Castrop'),
    ('KOR16', 'Donggyeong Lee'),
    ('KOR17', 'Guesung Cho'),
    ('KOR18', 'Heungmin Son'),
    ('KOR19', 'Heechan Hwang'),
    ('KOR20', 'Hyeongyu Oh')
)
update public.stickers
set
  nome = sticker_names.nome,
  updated_at = now()
from sticker_names
where public.stickers.codigo = sticker_names.codigo;
