alter table public.stickers
  add column if not exists nome text;

with sticker_names(codigo, nome) as (
  values
    ('ESP13', 'Team Photo'),
    ('ESP14', 'Mikel Merino'),
    ('ESP15', 'Lamine Yamal'),
    ('ESP16', 'Dani Olmo'),
    ('ESP17', 'Nico Williams'),
    ('ESP18', 'Ferran Torres'),
    ('ESP19', 'Álvaro Morata'),
    ('ESP20', 'Mikel Oyarzabal'),
    ('CPV1', 'Cape Verde Emblem'),
    ('CPV2', 'Vozinha'),
    ('CPV3', 'Logan Costa'),
    ('CPV4', 'Pico'),
    ('CPV5', 'Diney'),
    ('CPV6', 'Steven Moreira'),
    ('CPV7', 'Wagner Pina'),
    ('CPV8', 'João Paulo'),
    ('CPV9', 'Yannick Semedo'),
    ('CPV10', 'Kevin Pina'),
    ('CPV11', 'Patrick Andrade'),
    ('CPV12', 'Jamiro Monteiro'),
    ('CPV13', 'Team Photo'),
    ('CPV14', 'Deroy Duarte'),
    ('CPV15', 'Garry Rodrigues'),
    ('CPV16', 'Jovane Cabral'),
    ('CPV17', 'Ryan Mendes'),
    ('CPV18', 'Dailon Livramento'),
    ('CPV19', 'Willy Semedo'),
    ('CPV20', 'Bebé'),
    ('KSA1', 'Saudi Arabia Emblem'),
    ('KSA2', 'Nawaf Alaqidi'),
    ('KSA3', 'Abdulrahman AlSanbi'),
    ('KSA4', 'Saud Abdulhamid'),
    ('KSA5', 'Nawaf Buwashl'),
    ('KSA6', 'Jehad Thakri'),
    ('KSA7', 'Moteb AlHarbi'),
    ('KSA8', 'Hassan AlTambakti'),
    ('KSA9', 'Musab AlJuwayr'),
    ('KSA10', 'Ziyad AlJohani'),
    ('KSA11', 'Abdullah AlKhaibari'),
    ('KSA12', 'Nasser AlDawsari'),
    ('KSA13', 'Team Photo'),
    ('KSA14', 'Saleh Abu AlShamat'),
    ('KSA15', 'Marwan AlSahafi'),
    ('KSA16', 'Salem AlDawsari'),
    ('KSA17', 'Abdulrahman AlObud'),
    ('KSA18', 'Feras AlBrikan'),
    ('KSA19', 'Saleh AlShehri'),
    ('KSA20', 'Abdullah Al-Hamdan'),
    ('URU1', 'Uruguay Emblem'),
    ('URU2', 'Sergio Rochet'),
    ('URU3', 'Santiago Mele'),
    ('URU4', 'Ronald Araújo'),
    ('URU5', 'José María Giménez'),
    ('URU6', 'Sebastián Cáceres'),
    ('URU7', 'Mathías Olivera'),
    ('URU8', 'Guillermo Varela'),
    ('URU9', 'Nahitan Nández'),
    ('URU10', 'Federico Valverde'),
    ('URU11', 'Giorgian De Arrascaeta'),
    ('URU12', 'Rodrigo Bentancur'),
    ('URU13', 'Team Photo'),
    ('URU14', 'Manuel Ugarte'),
    ('URU15', 'Nicolás De La Cruz'),
    ('URU16', 'Maxi Araújo'),
    ('URU17', 'Darwin Núñez'),
    ('URU18', 'Federico Viñas'),
    ('URU19', 'Rodrigo Aguirre'),
    ('URU20', 'Facundo Pellistri'),
    ('FRA1', 'France Emblem'),
    ('FRA2', 'Mike Maignan'),
    ('FRA3', 'Théo Hernández'),
    ('FRA4', 'William Saliba'),
    ('FRA5', 'Jules Koundé'),
    ('FRA6', 'Ibrahima Konaté'),
    ('FRA7', 'Dayot Upamecano'),
    ('FRA8', 'Lucas Digne'),
    ('FRA9', 'Aurélien Tchouaméni'),
    ('FRA10', 'Eduardo Camavinga'),
    ('FRA11', 'Manu Koné'),
    ('FRA12', 'Adrien Rabiot'),
    ('FRA13', 'Team Photo'),
    ('FRA14', 'Michael Olise'),
    ('FRA15', 'Ousmane Dembélé'),
    ('FRA16', 'Bradley Barcola'),
    ('FRA17', 'Désiré Doué'),
    ('FRA18', 'Kingsley Coman'),
    ('FRA19', 'Hugo Ekitiké'),
    ('FRA20', 'Kylian Mbappé'),
    ('SEN1', 'Senegal Emblem'),
    ('SEN2', 'Édouard Mendy'),
    ('SEN3', 'Yehvann Diouf'),
    ('SEN4', 'Moussa Niakhaté'),
    ('SEN5', 'Abdoulaye Seck'),
    ('SEN6', 'Ismail Jakobs'),
    ('SEN7', 'El Hadji Malick Diouf'),
    ('SEN8', 'Kalidou Koulibaly'),
    ('SEN9', 'Idrissa Gana Gueye'),
    ('SEN10', 'Pape Matar Sarr'),
    ('SEN11', 'Pape Gueye'),
    ('SEN12', 'Habib Diarra'),
    ('SEN13', 'Team Photo'),
    ('SEN14', 'Lamine Camara'),
    ('SEN15', 'Sadio Mané'),
    ('SEN16', 'Ismaïla Sarr'),
    ('SEN17', 'Boulaye Dia'),
    ('SEN18', 'Iliman Ndiaye'),
    ('SEN19', 'Nicolas Jackson'),
    ('SEN20', 'Krépin Diatta'),
    ('IRQ1', 'Iraq Emblem'),
    ('IRQ2', 'Jalal Hassan'),
    ('IRQ3', 'Rebin Sulaka'),
    ('IRQ4', 'Hussein Ali'),
    ('IRQ5', 'Akam Hashem'),
    ('IRQ6', 'Merchas Doski'),
    ('IRQ7', 'Zaid Tahseen'),
    ('IRQ8', 'Manaf Younis'),
    ('IRQ9', 'Zidane Iqbal'),
    ('IRQ10', 'Amir Al-Ammari'),
    ('IRQ11', 'Ibrahim Bayesh'),
    ('IRQ12', 'Ali Jasim'),
    ('IRQ13', 'Team Photo'),
    ('IRQ14', 'Youssef Amyn'),
    ('IRQ15', 'Aimar Sher'),
    ('IRQ16', 'Marko Farji'),
    ('IRQ17', 'Osama Rashid'),
    ('IRQ18', 'Ali Al-Hamadi'),
    ('IRQ19', 'Aymen Hussein'),
    ('IRQ20', 'Mohanad Ali'),
    ('NOR1', 'Norway Emblem'),
    ('NOR2', 'Ørjan Nyland'),
    ('NOR3', 'Julian Ryerson'),
    ('NOR4', 'Leo Østigård'),
    ('NOR5', 'Kristoffer Vassbakk Ajer'),
    ('NOR6', 'Marcus Holmgren Pedersen'),
    ('NOR7', 'David Møller Wolfe'),
    ('NOR8', 'Torbjørn Heggem'),
    ('NOR9', 'Morten Thorsby'),
    ('NOR10', 'Martin Ødegaard'),
    ('NOR11', 'Sander Berge'),
    ('NOR12', 'Andreas Schjelderup'),
    ('NOR13', 'Team Photo'),
    ('NOR14', 'Patrick Berg'),
    ('NOR15', 'Erling Haaland'),
    ('NOR16', 'Alexander Sørloth'),
    ('NOR17', 'Aron Dønnum'),
    ('NOR18', 'Jørgen Strand Larsen'),
    ('NOR19', 'Antonio Nusa'),
    ('NOR20', 'Oscar Bobb'),
    ('ARG1', 'Argentina Emblem'),
    ('ARG2', 'Emiliano Martínez'),
    ('ARG3', 'Nahuel Molina'),
    ('ARG4', 'Cristian Romero'),
    ('ARG5', 'Nicolás Otamendi'),
    ('ARG6', 'Nicolás Tagliafico'),
    ('ARG7', 'Leonardo Balerdi'),
    ('ARG8', 'Enzo Fernández'),
    ('ARG9', 'Alexis Mac Allister'),
    ('ARG10', 'Rodrigo De Paul'),
    ('ARG11', 'Exequiel Palacios'),
    ('ARG12', 'Leandro Paredes'),
    ('ARG13', 'Team Photo'),
    ('ARG14', 'Nico Paz'),
    ('ARG15', 'Franco Mastantuono'),
    ('ARG16', 'Nicolás González'),
    ('ARG17', 'Lionel Messi'),
    ('ARG18', 'Lautaro Martínez'),
    ('ARG19', 'Julián Álvarez'),
    ('ARG20', 'Giuliano Simeone'),
    ('ALG1', 'Algeria Emblem'),
    ('ALG2', 'Alexis Guendouz'),
    ('ALG3', 'Ramy Bensebaini'),
    ('ALG4', 'Youcef Atal'),
    ('ALG5', 'Rayan Aït-Nouri'),
    ('ALG6', 'Mohamed Amine Tougai'),
    ('ALG7', 'Aïssa Mandi'),
    ('ALG8', 'Ismaël Bennacer'),
    ('ALG9', 'Houssem Aouar'),
    ('ALG10', 'Hicham Boudaoui'),
    ('ALG11', 'Ramiz Zerrouki'),
    ('ALG12', 'Nabil Bentaleb'),
    ('ALG13', 'Team Photo'),
    ('ALG14', 'Farès Chaïbi'),
    ('ALG15', 'Riyad Mahrez'),
    ('ALG16', 'Saïd Benrahma'),
    ('ALG17', 'Anis Hadj Moussa'),
    ('ALG18', 'Amine Gouiri'),
    ('ALG19', 'Baghdad Bounedjah'),
    ('ALG20', 'Mohamed Amoura'),
    ('AUT1', 'Austria Emblem'),
    ('AUT2', 'Alexander Schlager'),
    ('AUT3', 'Patrick Pentz'),
    ('AUT4', 'David Alaba'),
    ('AUT5', 'Kevin Danso'),
    ('AUT6', 'Philipp Lienhart'),
    ('AUT7', 'Stefan Posch'),
    ('AUT8', 'Philipp Mwene'),
    ('AUT9', 'Alexander Prass'),
    ('AUT10', 'Xaver Schlager'),
    ('AUT11', 'Marcel Sabitzer'),
    ('AUT12', 'Konrad Laimer'),
    ('AUT13', 'Team Photo'),
    ('AUT14', 'Florian Grillitsch'),
    ('AUT15', 'Nicolas Seiwald'),
    ('AUT16', 'Romano Schmid'),
    ('AUT17', 'Patrick Wimmer'),
    ('AUT18', 'Christoph Baumgartner'),
    ('AUT19', 'Michael Gregoritsch'),
    ('AUT20', 'Marko Arnautović'),
    ('JOR1', 'Jordan Emblem'),
    ('JOR2', 'Yazeed Abulaila'),
    ('JOR3', 'Ihsan Haddad'),
    ('JOR4', 'Mohammad Abu Hashish'),
    ('JOR5', 'Yazan Al-Arab'),
    ('JOR6', 'Abdallah Nasib'),
    ('JOR7', 'Saleem Obeid'),
    ('JOR8', 'Mohammad Abu Alnadi'),
    ('JOR9', 'Ibrahim Saadeh'),
    ('JOR10', 'Nizar Al-Rashdan'),
    ('JOR11', 'Noor Al-Rawabdeh'),
    ('JOR12', 'Mohannad Abu Taha'),
    ('JOR13', 'Team Photo'),
    ('JOR14', 'Amer Jamous'),
    ('JOR15', 'Mousa Al-Taamari'),
    ('JOR16', 'Yazan Al-Naimat'),
    ('JOR17', 'Mahmoud Al-Mardi'),
    ('JOR18', 'Ali Olwan'),
    ('JOR19', 'Mohammad Abu Zrayq'),
    ('JOR20', 'Ibrahim Sabra'),
    ('POR1', 'Portugal Emblem'),
    ('POR2', 'Diogo Costa'),
    ('POR3', 'José Sá'),
    ('POR4', 'Rúben Dias'),
    ('POR5', 'João Cancelo'),
    ('POR6', 'Diogo Dalot'),
    ('POR7', 'Nuno Mendes'),
    ('POR8', 'Gonçalo Inácio'),
    ('POR9', 'Bernardo Silva'),
    ('POR10', 'Bruno Fernandes'),
    ('POR11', 'Rúben Neves'),
    ('POR12', 'Vitinha'),
    ('POR13', 'Team Photo'),
    ('POR14', 'João Neves'),
    ('POR15', 'Cristiano Ronaldo'),
    ('POR16', 'Francisco Trincão'),
    ('POR17', 'João Félix'),
    ('POR18', 'Gonçalo Ramos'),
    ('POR19', 'Pedro Neto'),
    ('POR20', 'Rafael Leão'),
    ('COD1', 'DR Congo Emblem'),
    ('COD2', 'Lionel Mpasi'),
    ('COD3', 'Aaron Wan-Bissaka'),
    ('COD4', 'Axel Tuanzebe'),
    ('COD5', 'Arthur Masuaku'),
    ('COD6', 'Chancel Mbemba'),
    ('COD7', 'Joris Kayembe'),
    ('COD8', 'Charles Pickel'),
    ('COD9', 'Ngaliavel Mukau'),
    ('COD10', 'Edo Kayembe'),
    ('COD11', 'Samuel Moutoussamy'),
    ('COD12', 'Noah Sadiki'),
    ('COD13', 'Team Photo'),
    ('COD14', 'Théo Bongonda'),
    ('COD15', 'Meschack Elia'),
    ('COD16', 'Yoane Wissa'),
    ('COD17', 'Brian Cipenga'),
    ('COD18', 'Fiston Mayele'),
    ('COD19', 'Cédric Bakambu'),
    ('COD20', 'Nathanaël Mbuku'),
    ('UZB1', 'Uzbekistan Emblem'),
    ('UZB2', 'Utkir Yusupov'),
    ('UZB3', 'Farrukh Sayfiev'),
    ('UZB4', 'Sherzod Nasrullaev'),
    ('UZB5', 'Umar Eshmurodov'),
    ('UZB6', 'Husniddin Alikulov'),
    ('UZB7', 'Rustam Ashurmatov'),
    ('UZB8', 'Khojiakbar Alijonov'),
    ('UZB9', 'Abdukodir Khusanov'),
    ('UZB10', 'Odiljon Hamrobekov'),
    ('UZB11', 'Otabek Shukurov'),
    ('UZB12', 'Jamshid Iskanderov'),
    ('UZB13', 'Team Photo'),
    ('UZB14', 'Azizbek Turgunboev'),
    ('UZB15', 'Khojimat Erkinov'),
    ('UZB16', 'Eldor Shomurodov'),
    ('UZB17', 'Oston Urunov'),
    ('UZB18', 'Jaloliddin Masharipov'),
    ('UZB19', 'Igor Sergeev'),
    ('UZB20', 'Abbosbek Fayzullaev'),
    ('COL1', 'Colombia Emblem'),
    ('COL2', 'Camilo Vargas'),
    ('COL3', 'David Ospina'),
    ('COL4', 'Davinson Sánchez'),
    ('COL5', 'Yerry Mina'),
    ('COL6', 'Daniel Muñoz'),
    ('COL7', 'Johan Mojica'),
    ('COL8', 'Jhon Lucumí'),
    ('COL9', 'Santiago Arias'),
    ('COL10', 'Jefferson Lerma'),
    ('COL11', 'Kevin Castaño'),
    ('COL12', 'Richard Ríos'),
    ('COL13', 'Team Photo'),
    ('COL14', 'James Rodríguez'),
    ('COL15', 'Juan Fernando Quintero'),
    ('COL16', 'Jorge Carrascal'),
    ('COL17', 'Jhon Arias'),
    ('COL18', 'Jhon Córdoba'),
    ('COL19', 'Luis Suárez'),
    ('COL20', 'Luis Díaz'),
    ('ENG1', 'England Emblem'),
    ('ENG2', 'Jordan Pickford'),
    ('ENG3', 'John Stones'),
    ('ENG4', 'Marc Guéhi'),
    ('ENG5', 'Ezri Konsa'),
    ('ENG6', 'Trent Alexander-Arnold'),
    ('ENG7', 'Reece James'),
    ('ENG8', 'Dan Burn'),
    ('ENG9', 'Jordan Henderson'),
    ('ENG10', 'Declan Rice'),
    ('ENG11', 'Jude Bellingham'),
    ('ENG12', 'Cole Palmer'),
    ('ENG13', 'Team Photo'),
    ('ENG14', 'Morgan Rogers'),
    ('ENG15', 'Anthony Gordon'),
    ('ENG16', 'Phil Foden'),
    ('ENG17', 'Bukayo Saka'),
    ('ENG18', 'Harry Kane'),
    ('ENG19', 'Marcus Rashford'),
    ('ENG20', 'Ollie Watkins'),
    ('CRO1', 'Croatia Emblem'),
    ('CRO2', 'Dominik Livaković'),
    ('CRO3', 'Duje Ćaleta-Car'),
    ('CRO4', 'Joško Gvardiol'),
    ('CRO5', 'Josip Stanišić'),
    ('CRO6', 'Luka Vušković'),
    ('CRO7', 'Josip Šutalo'),
    ('CRO8', 'Kristijan Jakić'),
    ('CRO9', 'Luka Modrić'),
    ('CRO10', 'Mateo Kovačić'),
    ('CRO11', 'Martin Baturina'),
    ('CRO12', 'Lovro Majer'),
    ('CRO13', 'Team Photo'),
    ('CRO14', 'Mario Pašalić'),
    ('CRO15', 'Petar Sučić'),
    ('CRO16', 'Ivan Perišić'),
    ('CRO17', 'Marco Pašalić'),
    ('CRO18', 'Ante Budimir'),
    ('CRO19', 'Andrej Kramarić'),
    ('CRO20', 'Franjo Ivanović'),
    ('GHA1', 'Ghana Emblem'),
    ('GHA2', 'Lawrence Ati Zigi'),
    ('GHA3', 'Tariq Lamptey'),
    ('GHA4', 'Mohammed Salisu'),
    ('GHA5', 'Alidu Seidu'),
    ('GHA6', 'Alexander Djiku'),
    ('GHA7', 'Gideon Mensah'),
    ('GHA8', 'Caleb yirenkyi'),
    ('GHA9', 'Abdul Issahaku Fatawu'),
    ('GHA10', 'Thomas Partey'),
    ('GHA11', 'Salis Abdul Samed'),
    ('GHA12', 'Kamaldeen Sulemana'),
    ('GHA13', 'Team Photo'),
    ('GHA14', 'Mohammed Kudus'),
    ('GHA15', 'Iñaki Williams'),
    ('GHA16', 'Jordan Ayew'),
    ('GHA17', 'André Ayew'),
    ('GHA18', 'Joseph Paintsil'),
    ('GHA19', 'Osman Bukari'),
    ('GHA20', 'Antone Semenyo'),
    ('PAN1', 'Panama Emblem'),
    ('PAN2', 'Orlando Mosquera'),
    ('PAN3', 'Luis Mejía'),
    ('PAN4', 'Fidel Escobar'),
    ('PAN5', 'Andrés Andrade'),
    ('PAN6', 'Michael Amir Murillo'),
    ('PAN7', 'Eric Davis'),
    ('PAN8', 'José Córdoba'),
    ('PAN9', 'César Blackman'),
    ('PAN10', 'Cristian Martínez'),
    ('PAN11', 'Aníbal Godoy'),
    ('PAN12', 'Adalberto Carrasquilla'),
    ('PAN13', 'Team Photo'),
    ('PAN14', 'Édgar Bárcenas'),
    ('PAN15', 'Carlos Harvey'),
    ('PAN16', 'Ismael Díaz'),
    ('PAN17', 'José Fajardo'),
    ('PAN18', 'Cecilio Waterman'),
    ('PAN19', 'José Luis Rodríguez'),
    ('PAN20', 'Alberto Quintero'),
    ('CC1', 'Lamine Yamal'),
    ('CC2', 'Joshua Kimmich'),
    ('CC3', 'Harry Kane'),
    ('CC4', 'Santiago Giménez'),
    ('CC5', 'Joško Gvardiol'),
    ('CC6', 'Federico Valverde'),
    ('CC7', 'Jefferson Lerma'),
    ('CC8', 'Enner Valencia'),
    ('CC9', 'Gabriel Magalhães'),
    ('CC10', 'Virgil Van Dijk'),
    ('CC11', 'Alphonso Davies'),
    ('CC12', 'Emiliano Martinez'),
    ('CC13', 'Raúl Jiménez'),
    ('CC14', 'Lautaro Martinez')
)
update public.stickers
set
  nome = sticker_names.nome,
  updated_at = now()
from sticker_names
where public.stickers.codigo = sticker_names.codigo;
